#!/bin/sh
# Generate build.ninja from the current src tree.
# Each src/**.c compiles freestanding to build/<path>.o (path-qualified,
# avoids basename collisions), same flags as `just build`. ninja handles
# incremental + parallel via the per-object depfile.
set -eu

cc="${CC:-clang}"
# cflags come from justfile (single source of truth), passed via CFLAGS by `just ninja`.
: "${CFLAGS:?CFLAGS not set -- run via 'just ninja'}"
cflags="$CFLAGS"

{
    echo "# generated by scripts/gen_ninja.sh -- do not edit"
    echo "cc = $cc"
    echo "cflags = $cflags"
    echo "rule cc"
    echo "  command = \$cc \$cflags -MD -MF \$out.d -c \$in -o \$out"
    echo "  depfile = \$out.d"
    echo "  deps = gcc"
    echo "  description = CC \$out"
    find src -name '*.c' | sort | while read -r f; do
        echo "build build/${f%.c}.o: cc $f"
    done
} > build.ninja
